# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-ast
        name: Check python ast (with Python 2.7)
        language_version: python2.7
        stages: [manual]
    -   id: check-ast
        name: Check python ast (with Python 3)
        language_version: python3
        stages: [manual]
-   repo: local
    hooks:
    -   id: prettify
        name: Run prettify
        entry: ./tools/prettify/prettify.py
        language: script
        files: '.*\.(F|f90)$'
        exclude: >-
          (?x)^(
            tools/.*|
            src/base/base_uses.f90|
            src/common/util.F|
          )$
